version: '3'
services:
  app:
    build: "./app"
    container_name: "twitter_app"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./:/project"
    command: "bash -c 'cd /project/app && npm start'"
    tty: true